export type Activity = {
  id: string;
  type: 'call' | 'meeting' | 'email' | 'note' | 'status_change' | 'follow_up';
  date: string;
  time?: string;
  notes?: string;
  outcome?: string;
  startTime?: string;
  endTime?: string;
  duration?: number;
  assignedTo?: string;
  nextAction?: string;
  next_action_date?: string;
  contactPerson?: string;
  location?: string;
  callType?: 'incoming' | 'outgoing';
  description?: string;
  teamMember?: string;
  leadName?: string;
  activityType?: string;
  activityOutcome?: string;
  activityNextAction?: string;
  activityNextActionDate?: string;
  update?: string;
};